### ISSUE TITLE
Feature request - Disable option

### ISSUE THREAD

**Issue by sinoergin** [brianvoe/slim-select#117]
Hi there,

I have 3 dropdowns back to back that allow the user to choose from (each dropdown offers the same 10 options to the user) and I am trying to disable the selection made in the previous dropdown so that the same metric cannot be chosen more than once. Is there any way you can add a “disable option” to the dropdown options so that I can have the first selection made in the dropdown not to appear/ or be disabled in the second dropdown and so on.

Thanks

**Comment by brianvoe** [comment]
If i am following you correctly you want to specifically disable a single option in the dropdown. In order to do that you can just update your select dropdown and set one of your options to disabled, slim select should pick up on the change and update accordingly. The other way to do it is use the data option and programmable set your data and when you need to update your data set with a one of your options that is disabled just use setData with that option set to disabled.

Hope that helps. Be sure to look at the docs there are a lot of examples there to help you understand what its capable of doing.

**Comment by sinoergin** [comment]
I tried your recommendation but it still didnt work... when i setData to disabled the option is still clickable. Is there another way to set an option as disabled? Also, in my case I have one more dropdowns working simultaneously so the setData disabled option needs to refresh with every selection. 

I think you can do this;

> src/slim-select/data.ts

`public setDisabled(value: string | string[], type = 'value', disabled: boolean = false): void {`
    `// do stuff`
`}`

**Comment by sinoergin** [comment]
I tried your recommendation but it still didnt work... when i setData to disabled the option is still clickable. Is there another way to set an option as disabled? Also, in my case I have one more dropdowns working simultaneously so the setData disabled option needs to refresh with every selection.

I think you can do this;

> src/slim-select/data.ts

`public setDisabled(value: string | string[], type = 'value', disabled: boolean = false): void {`
         `   // do stuff`
`}`

**Comment by brianvoe** [comment]
oh i see what your trying to do. Ill double check to make sure option individually can be disabled.

**Comment by brianvoe** [comment]
I found out that disabled/selected options where still allowed to be clicked on. I fixed that and pushed v1.20.0. I didnt specifically add a setDisabled method cause you can use setData or update your original select  to accomplish the same thing.

Let me know if this solves your issues.

Thanks for catching this!!!

**Comment by sinoergin** [comment]
OK dude. No problem, i can do it. 
But maybe you can add your source;
`.ss-disabled {`
       `    cursor:not-allowed;`
       `    pointer-events:none;`
`}`

**Comment by konstantin83** [comment]
Hey! Thanks for your amazing module. It's awesome!
Google this issue because of possibly the same problem:

2 slim select elements based on html <select> and <option> inside them.

I want to filter elements in second slim select after choosing option in the first one.

Tried adding disabled attribute to second slim select's <option> tags. But seems like it doesn't sync with select after it was generated.

Is there any way to sync with original <select> and it's <option> after slim select object is generated?

Tried to find method like rerender or update, but found nothing.

Would appreciate any help, thank you!

**Comment by brianvoe** [comment]
Thanks for your issue but right now im spending time on building the next version and have stopped development on this version. Keep in touch with the next version release

**Comment by konstantin83** [comment]
Glad to hear that. Looking forward to a new version.

But maybe you could suggest a solution on how to disable some option in slim select by disabling the source select option?

I'm very middle in JS and still can't figure it out myself

**Comment by brianvoe** [comment]
if your using normal select dropdown its just <options disabled></option>. If your using data set disabled=true

**Comment by konstantin83** [comment]
Yes, I'm using only normal select. Here's the code https://jsfiddle.net/salah_k/f9Lnhzju/3/ 
Maybe disabling must be done some other way for slim select to recognize update

**Comment by konstantin83** [comment]
This is the only solution I figured out logically. http://joxi.ru/BA0EwyQtpd91nr?d=1
Is it lame? )
